# Generated by Django 3.2.13 on 2022-11-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Where_is_teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='contributor',
            field=models.CharField(default='NULL', max_length=20, verbose_name='countributor'),
        ),
    ]
