# Generated by Django 3.2.13 on 2022-11-09 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Where_is_teacher', '0004_alter_teacher_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='image',
        ),
    ]
