# Generated by Django 3.2.13 on 2022-11-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Where_is_teacher', '0002_teacher_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='NULL', upload_to='static/Where_is_teacher/images'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='contributor',
            field=models.CharField(max_length=20, verbose_name='contributor'),
        ),
    ]
