# Generated by Django 3.2.13 on 2022-11-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Where_is_teacher', '0006_sort'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sort',
        ),
        migrations.AddField(
            model_name='teacher',
            name='sort',
            field=models.IntegerField(choices=[(0, 'なし'), (1, '学科別'), (2, '五十音')], default=0, verbose_name='sort'),
        ),
    ]
