# Generated by Django 4.1.3 on 2023-01-29 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Where_is_teacher', '0008_auto_20221123_1122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sort',
        ),
    ]
